version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - "3307:3306"  # Endret port fra 3306 til 3307 for å unngå konflikt
    environment:
      MYSQL_ROOT_PASSWORD: example

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Justert port for web-applikasjonen
